[package]
name = "rtm"
version = "0.1.0"
authors = ["Alexey Novakov <novakov.alex at gmail com>"]

[dependencies]
chrono = "0.4.2"
diesel = { version = "1.0.0", features = ["postgres", "chrono"] }
dotenv = "0.9.0"