version: '2'
services:

  postgres:
    image: postgres:10.4
    container_name: postgres
    mem_limit: 1g
    environment:
      POSTGRES_PASSWORD: "tc"
      POSTGRES_USER: "tc"
      POSTGRES_DB: "rtm"
    ports:
      - 5432:5432

  rtm:
    image: rtm:0.1.0
    container_name: rtm
    environment:
      DATABASE_URL: "postgres://tc:tc@postgres/rtm"
      ROCKET_ADDRESS: 0.0.0.0
      ROCKET_ENV: "production"
    ports:
      - 8000:80
    depends_on:
      - postgres